name: app-extension-libs

type: node

up:
  - git_hooks:
      commit-msg: ./scripts/commitlint.sh
      pre-commit: ./scripts/prettier.sh
  - railgun
  - node:
      version: v12.11.1
      yarn: true
      packages:
        - .
  - custom:
      name: Install playground dependencies
      met?: test -d ./playground/node_modules
      meet: cd ./playground && yarn

commands:
  boot: yarn run bootstrap
  console: node
  server: yarn run server
  build: yarn run build
  nuke: yarn cache clean && rm -rf ./node_modules && rm -rf ./playground/node_modules
  test: yarn run test

open:
  app: https://app-extension-libs.myshopify.io
